#!/bin/bash

cmake \
	-DCMAKE_INSTALL_PREFIX:PATH=/usr \
	-DCMAKE_BUILD_TYPE=Release \
	-DPARAVIEW_BUILD_QT_GUI=ON \
	-DPARAVIEW_ENABLE_CATALYST=ON \
	-DPARAVIEW_ENABLE_PYTHON=ON \
	-DPARAVIEW_INSTALL_DEVELOPMENT_FILES=ON \
	-DBUILD_TESTING=OFF \
	$*
