#!/bin/bash

cmake \
	-DCMAKE_INSTALL_PREFIX:PATH=/opt/paraview-offscreen \
        -DCPACK_SET_DESTDIR=TRUE \
	-DCPACK_INSTALL_PREFIX:PATH=/opt/paraview-offscreen \
	-DCPACK_PACKAGING_INSTALL_PREFIX:PATH=/opt/paraview-offscreen \
	-DCMAKE_BUILD_TYPE=Release \
	-DPARAVIEW_BUILD_QT_GUI=OFF \
	-DPARAVIEW_ENABLE_CATALYST=ON \
	-DPARAVIEW_ENABLE_PYTHON=ON \
	-DPARAVIEW_INSTALL_DEVELOPMENT_FILES=ON \
	-DBUILD_TESTING=OFF \
	-DVTK_OPENGL_HAS_OSMESA=ON \
	-DVTK_USE_X=OFF \
	$*
